version: '3.7'
services:
  ldap_server:
    image: osixia/openldap:latest
    command:
      - --loglevel
      - debug
    environment:
      #DISABLE_CHOWN: "true"
      #LDAP_LOG_LEVEL: "256"
      #LDAP_READONLY_USER: "false"
      #LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_SEED_INTERNAL_LDIF_PATH: /resources/
      LDAP_ORGANISATION: "RUAT DEVELOP"
      LDAP_DOMAIN: "ruat.gob.bo"
      LDAP_ADMIN_PASSWORD: openldap
      LDAP_BASE_DN: dc=ruat,dc=gob,dc=bo
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ./ldif:/resources/
      #- ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config: