version: '3.7'
services:
  ldap_server:
    image: galiaga/openldap-data:0.0.1
    environment:
      LDAP_ADMIN_PASSWORD: openldap
      LDAP_BASE_DN: dc=ruat,dc=gob,dc=bo
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    entrypoint: /container/tool/run --loglevel=debug
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config: